version: '2.1'
services:
  platform-configuration:
    image: kicey/bs-platform-config:origin
    restart: always
    ports:
      - 8888:8888

  platform-registry:
    image: kicey/bs-platform-registry:origin
    environment:
      CONFIG_HOST: platform-configuration
    restart: always
    depends_on:
      platform-configuration:
        condition: service_healthy
    ports:
      - 8761:8761

  platform-gateway:
    image: kicey/bs-platform-gateway:origin
    depends_on:
      platform-configuration:
        condition: service_healthy
      platform-registry:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
    restart: always
    ports:
      - 8080:8080

  domain-security:
    image: kicey/bs-security:origin
    depends_on:
      platform-configuration:
        condition: service_healthy
      platform-registry:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
    restart: always
    ports:
      - 8301:8301

  domain-account:
    image: kicey/bs-account:origin
    depends_on:
      platform-configuration:
        condition: service_healthy
      platform-registry:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8401:8401

  domain-warehouse:
    image: kicey/bs-warehouse:origin
    depends_on:
      platform-configuration:
        condition: service_healthy
      platform-registry:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8501:8501

  domain-payment:
    image: kicey/bs-payment:origin
    depends_on:
      platform-configuration:
        condition: service_healthy
      platform-registry:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8601:8601
