eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/eureka/

spring:
  cloud:
    gateway:
      locators:
        enabled: true
      routes:
        - id: account
          predicates:
            - Path=/restful/accounts/**
          uri: lb://account

        - id: payment
          predicates:
            - Path=/restful/pay/**
          uri: lb://payment

        - id: settlement
          predicates:
            - Path=/restful/settlements/**
          uri: lb://payment

        - id: advertisements
          predicates:
            - Path=/restful/advertisements/**
          uri: lb://warehouse

        - id: products
          predicates:
            - Path=/restful/products/**
          uri: lb://warehouse

        - id: security
          predicates:
            - Path=/oauth/**
          uri: lb://security
        
server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
